---
- name: This sets up an Apache web server
  hosts: aws_ec2
  become: yes
  remote_user: ubuntu
  gather_facts: true
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/jomin-key-pair.pem"  
    ansible_ssh_user: "ubuntu"
  tasks:
    - name: "Install apache2 and php packages"
      apt:
        name:
          - "apache2"
          - "php"
        state: present
        update_cache: yes
        
    - name: "Copy code from GitHub"
      get_url:
        url: https://www.shubhammishra.in
        dest: "/var/www/html/index.php"
        
    - name: "Start apache2 service"
      service:
        name: apache2
        state: started
        
    - name: APT Install Packages
      apt: 
        name: "{{ item }}"
        state: latest
      loop:
        - wget
        
    - name: Terraform install
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.9.1/terraform_0.9.1_linux_amd64.zip
        dest: /usr/bin
        remote_src: true
